name: gowayanad
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  geolocator: ^14.0.2
  geocoding: ^3.0.0
  timeago: ^3.7.1
  url_launcher: ^6.3.1
  csv: ^7.2.0
  file_picker: ^10.3.10
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  google_maps_flutter: ^2.10.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/welcome_bg.png