name: CI Pipeline

on:
  push:
    branches:
      - admin-panel
      - backup-before-reset
      - current_locatiom
      - dynamic-pin
      - fair-calculation
      - main
      - new_branch
      - old-working-dynamic
  pull_request:
    branches:
      - admin-panel
      - backup-before-reset
      - current_locatiom
      - dynamic-pin
      - fair-calculation
      - main
      - new_branch
      - old-working-dynamic

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: echo "CI is running on branch ${{ github.ref }} 🚀"