on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Flutter Doctor
      run: flutter doctor

    - name: Install dependencies
      run: flutter pub get

    - name: Analyze project
      run: flutter analyze --no-fatal-infos --no-fatal-warnings

    - name: Run tests
      run: flutter test

    - name: Build APK (Android)
      run: flutter build apk --release

    - name: List Build Outputs
      run: ls -R build/app/outputs
      continue-on-error: true

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/*.apk

    - name: Authenticate to Google Cloud
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.CREDENTIAL_FILE_CONTENT }}

    - name: upload artifact to Firebase App Distribution
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
        groups: testers
        file: build/app/outputs/flutter-apk/app-release.apk
